# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [47]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [49]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [59]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [61]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [165]:
print(np.exp(B))
print()
print(np.min(B))
print()
print(np.min(B,axis=1))
print()
print(np.min(B,axis=0))
print()
print(np.argmin(B))
print()
print(np.argmin(B,axis=1))
print()
print(np.sum(B))
print()
print(np.mean(B, axis=0))
print()
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [172]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [174]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [183]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [185]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [187]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [189]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [191]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [193]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [195]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [70]:
import numpy as np

def add_mult_matrices(a, b, c):
    
    # Check if a and b are NumPy arrays 
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        raise ValueError("Warning !! You have to insert two arrays!!!")
        
    # Check if addition is possible 
    if c == 'add':
        if a.shape == b.shape:
            return a + b
        else:
            raise ValueError("Shapes of matrix 'a' and 'b' do not match for addition.")
            
    # Check if multiplication is possible 
    elif c == 'multiply':
        if a.shape[1] == b.shape[0]:
            return np.dot(a, b)
        else:
            raise ValueError("Number of columns in matrix 'a' must equal the number of rows in matrix 'b' for multiplication.")
    
    else:
        raise ValueError("You have to write 'add' or 'multiply'.")

# Example usage
A = np.array([[23, 9], [44, 12]])
B = np.array([[0, 3], [2, 90]])
result_add = add_mult_matrices(A, B, 'add')
print(result_add)
print()
result_multiply = add_mult_matrices(A, B, 'multiply')
print(result_multiply)

    

[[ 23  12]
 [ 46 102]]

[[  18  879]
 [  24 1212]]


In [161]:
a = np.arange(20).reshape(5, 4)
b= np.arange(40).reshape(4, 10)
print(a)
print()
print(b)
print()
add_mult_matrices(a,b,'multiply')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]



array([[ 140,  146,  152,  158,  164,  170,  176,  182,  188,  194],
       [ 380,  402,  424,  446,  468,  490,  512,  534,  556,  578],
       [ 620,  658,  696,  734,  772,  810,  848,  886,  924,  962],
       [ 860,  914,  968, 1022, 1076, 1130, 1184, 1238, 1292, 1346],
       [1100, 1170, 1240, 1310, 1380, 1450, 1520, 1590, 1660, 1730]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [100]:
print(' Uppgift 10.1.1. Definiera vektorn x enligt nedan.')
import numpy as np




x = (4, 3)

x = np.array([4, 3])
print()

print(' a) Vilken dimension har vektorn x?')

print(x.ndim)
print()
print('b) Ber¨akna 5x.')

A=np.dot(x,5)
print(A)
print()
print('c) Ber¨akna 3x.')

B=3*x
print(B)
print()
print('d) Ber¨akna 5x + 3x.')
print(A + B)
print()
print('e) Ber¨akna 8x.')

C=x*8
print(C)
print()
print('f) Ber¨akna 4x − x.')

D=x*4
print(D - x)
print()
print('g) Ber¨akna x⊤, vilken blir den nya dimensionen efter att transponeringen utf¨orts?')

x_transpose = x.T
print(x_transpose)
print() 
print(x_transpose.ndim)
print()       
print('h) ¨Ar x + x⊤ definierat?')

print( x.shape == x_transpose.shape)
print()
print('i) Ber¨akna ∥x∥.')

print(np.linalg.norm(x))
print()
print('Uppgift 10.1.2. Definiera vektorn v enligt nedan.')
v =np.array ( [[3] , [7] ,[0] ,[11]])
 
print('a) Vilken dimension har vektorn v?')

print(v.ndim)
print()
print('b) Ber¨akna 2v.')

print(v*2)
print()    
print('c) Ber¨akna 5v + 2v.')

print(5*v + 2*v)

print('d) Ber¨akna 4v − 2v.')
print()
print(4*v - 2*v)
print('e) Ber¨akna v⊤, vilken blir den nya dimensionen efter att transponeringen utf¨orts?')

v_transpose = v.T
print(v_transpose)
print()
print(v_transpose.ndim)
print()
print('f) Ber¨akna ∥v∥.')

print(np.linalg.norm(v))
print()
print('Uppgift 10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1).')
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

print('a) Ber¨akna ∥v1∥.')
v1_norm = np.linalg.norm(v1)
print(v1_norm)
print()
print('b) Ber¨akna ∥v1 − v2∥.')
v2_norm = np.linalg.norm(v2)
print((v1_norm) - (v2_norm))



 a) Vilken dimension har vektorn x?
1

b) Ber¨akna 5x.
[20 15]

c) Ber¨akna 3x.
[12  9]

d) Ber¨akna 5x + 3x.
[32 24]

e) Ber¨akna 8x.
[32 24]

f) Ber¨akna 4x − x.
[12  9]

g) Ber¨akna x⊤, vilken blir den nya dimensionen efter att transponeringen utf¨orts?
[4 3]

1

h) ¨Ar x + x⊤ definierat?
True

i) Ber¨akna ∥x∥.
5.0

Uppgift 10.1.2. Definiera vektorn v enligt nedan.
a) Vilken dimension har vektorn v?
2

b) Ber¨akna 2v.
[[ 6]
 [14]
 [ 0]
 [22]]

c) Ber¨akna 5v + 2v.
[[21]
 [49]
 [ 0]
 [77]]
d) Ber¨akna 4v − 2v.

[[ 6]
 [14]
 [ 0]
 [22]]
e) Ber¨akna v⊤, vilken blir den nya dimensionen efter att transponeringen utf¨orts?
[[ 3  7  0 11]]

2

f) Ber¨akna ∥v∥.
13.379088160259652

Uppgift 10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och v2 = (2, 3, 1, 1).
a) Ber¨akna ∥v1∥.
7.14142842854285

b) Ber¨akna ∥v1 − v2∥.
3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [165]:
print(' Ovningsuppgifter')

print('Uppgift 10.2.1. Definiera matriserna:')
print('A = ([[2, 1, 1] , [1, -1, 1]])')
print('B = ([[4, -2, 1] , [2, -4, -2]])')
print('C = ([[1, 2] , [2, 1]])')    
print('D = ([[3, 4] , [4, 3]])')
print('E = ([[1],[2]]) ')
print('I = ([[1, 0], [0, 1]])')
           
A = np.array([[2, 1, 1] , [1, -1, 1]])
B = np.array([[4, -2, 1] , [2, -4, -2]])
C = np.array([[1, 2] , [2, 1]])      
D = np.array([[3, 4] , [4, 3]])
E = np.array([[1],[2]])   
I = np.array([[1, 0], [0, 1]])

print('Om det ¨ar definierat, utf¨or f¨oljande ber¨akningar:')
print('a) 2A')
print(A * 2)
          
print('b) B − 2A')
print(B - (2 * A))
print('c) 3C − 2E')
print((3 * C) - (2 * E))

print(('d) 2D − 3C'))
print((2 * D) - (3 * C))


print('e) D⊤ + 2D')
D_transpose = D.T
print(D_transpose + (2 * D))


print('f) 2C⊤ − 2D⊤')
C_transpose = C.T
print((2 * C_transpose) - (2 * D_transpose))

print('g) A⊤ − B')
A_transpose = A.T
if (A_transpose.shape == B.shape):
    print(A_transpose - B)
else:
    print(' not definerat')

print('h) AC')
if A.shape[1] == B.shape[0]:
    print(A * C)
else:
    print('not definerat')
print('i) CD')
print(C * D)
print('j) CB')
if B.shape[1] == C.shape[0]:
    print(C * B)
else:
    print(' not definerat')
print('k) CI')
print(C * I)
print('l) AB⊤')
AB = A * B
AB_transpose = AB.T
print(AB_transpose)


print('Uppgift 10.2.2. Definiera matrisen')
A = np.array([[2, 3, 4], [5, 4, 1]])

print('Ber¨akna AAT .')
AA = A * A
print( AA.T)
        
print('Uppgift 10.2.3. Definiera matriserna')
import numpy as np

# Define the matrices A, B, and C
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print('Verifiera att AB = AC men att B != C. Vad vi vill demonstrera med detta exemplet ¨ar att vi har definierat ett nytt,matematiskt objekt (matriser i detta fallet) och att de ”vanliga reglerna” f¨or aritmetik som vi l¨art oss fr˚an grundskolan,inte n¨odv¨andigtvis g¨aller ¨aven h¨ar')



# Perform the matrix multiplications AB and AC
AB = np.dot(A, B)
AC = np.dot(A, C)

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C:")
print(C)

print("\nAB (A * B):")
print(AB)

print("\nAC (A * C):")
print(AC)

# Check if AB == AC and if B == C
print("\nIs AB equal to AC?", np.array_equal(AB, AC))
print("Is B equal to C?", np.array_equal(B, C))


 Ovningsuppgifter
Uppgift 10.2.1. Definiera matriserna:
A = ([[2, 1, 1] , [1, -1, 1]])
B = ([[4, -2, 1] , [2, -4, -2]])
C = ([[1, 2] , [2, 1]])
D = ([[3, 4] , [4, 3]])
E = ([[1],[2]]) 
I = ([[1, 0], [0, 1]])
Om det ¨ar definierat, utf¨or f¨oljande ber¨akningar:
a) 2A
[[ 4  2  2]
 [ 2 -2  2]]
b) B − 2A
[[ 0 -4 -1]
 [ 0 -2 -4]]
c) 3C − 2E
[[ 1  4]
 [ 2 -1]]
d) 2D − 3C
[[3 2]
 [2 3]]
e) D⊤ + 2D
[[ 9 12]
 [12  9]]
f) 2C⊤ − 2D⊤
[[-4 -4]
 [-4 -4]]
g) A⊤ − B
 not definerat
h) AC
not definerat
i) CD
[[3 8]
 [8 3]]
j) CB
 not definerat
k) CI
[[1 0]
 [0 1]]
l) AB⊤
[[ 8  2]
 [-2  4]
 [ 1 -2]]
Uppgift 10.2.2. Definiera matrisen
Ber¨akna AAT .
[[ 4 25]
 [ 9 16]
 [16  1]]
Uppgift 10.2.3. Definiera matriserna
Verifiera att AB = AC men att B != C. Vad vi vill demonstrera med detta exemplet ¨ar att vi har definierat ett nytt,matematiskt objekt (matriser i detta fallet) och att de ”vanliga reglerna” f¨or aritmetik som vi l¨art oss fr˚an grundskolan,inte n¨odv¨andigtvis g¨aller ¨aven h¨ar
Matrix A:
[[1

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [381]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [383]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [385]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
